### ISSUE TITLE
Complete Implementation of v0.1.0 - Tracking Issue

### ISSUE THREAD

**Issue by FlixCoder** [FlixCoder/sample-config#1]
- [x] Create first PoC for generating sample configs for structs
- [x] More implementations on standard types
  - [x] Vec
  - [x] Option
  - [x] Box
  - [x] PathBuf & co.
  - [x] SocketAddr
- [x] Basic enum derive support
- [x] Make ready for publishing (documentation) and publish
